name: 批量导入建木官方节点项目

trigger:
  type: webhook
  param:
    - name: gitee_token
      type: SECRET
      exp: $.header.X-Gitee-Token
    - name: gitee_event
      type: STRING
      exp: $.header.X-Gitee-Event
    - name: git_ref
      type: STRING
      exp: $.body.json.ref
    - name: pr_state
      type: STRING
      exp: $.body.json.pull_request.state
    - name: pr_target_branch
      type: STRING
      exp: $.body.json.target_branch
  auth:
    token: ${trigger.gitee_token}
    value: ((gitee.webhook_runner_token))
  only: (${trigger.gitee_event} == "Push Hook" && ${trigger.git_ref} == "refs/heads/master" || ${trigger.pr_target_branch} == "master" && ${trigger.pr_state} == "merged")

pipeline:
  git_clone:
    type: git_clone:1.2.0
    param:
      remote_url: https://gitee.com/jianmu-runners/jianmu-runner-list.git
      ref: refs/heads/master
  sync_project_group:
    type: sync_project_group:2.0.0
    param:
      ci_url: https://ci.jianmu.run
      ci_username: ((jianmu_ci.username))
      ci_password: ((jianmu_ci.password))
      git_path: ${git_clone.git_path}
      group_file_path: /project_group.yml
      deletable: false
