name: 发布git_push节点

global:
  param:
    # 格式：jianmurunner/${节点定义唯一标识}
    image_name: jianmurunner/git_push

trigger:
  type: webhook
  param:
    - name: gitee_token
      type: SECRET
      exp: $.header.X-Gitee-Token
    - name: gitee_event
      type: STRING
      exp: $.header.X-Gitee-Event
    - name: gitee_tag_created
      type: BOOL
      exp: $.body.json.created
    - name: gitee_ref
      type: STRING
      exp: $.body.json.[?(@.ref=~/^refs\/tags\/git_push>.*$/i)].ref
  auth:
    token: ${trigger.gitee_token}
    value: ((gitee.webhook_runner_token))
  only: (${trigger.gitee_event} === "Tag Push Hook" && ${trigger.gitee_tag_created} && ${trigger.gitee_ref} != "")

pipeline:
  git_clone:
    type: git_clone:1.2.0
    param:
      remote_url: https://gitee.com/jianmu-runners/jianmu-runner-git.git
      ref: ${trigger.gitee_ref}
  string:
    type: string:1.0.0-nodejs16.13.1
    param:
      expression: '"${git_clone.git_tag}".split(">")[1]'
  image_build:
    type: docker_image_build:1.0.1
    param:
      workspace: ${git_clone.git_path}
      docker_username: ((dockerhub.runner_user))
      docker_password: ((dockerhub.runner_pass))
      docker_file: dockerfile/Dockerfile
      image_name: ${global.image_name}
      image_tag: ${string.result}
      docker_build_path: .
  hub_publish:
    type: hub_publish:1.1.0
    param:
      hub_url: https://api.internal.jianmuhub.com
      dsl_file_path: ${git_clone.git_path}/dsl/git_push.yml
      hub_api_ak: ((jianmuhub.ak))
      hub_api_sk: ((jianmuhub.sk))
      version: ${string.result}
      image: ${global.image_name}:${string.result}
  send_message:
    type: feishu_notice_post:1.0.2
    param:
      bot_webhook_url: ((feishu.webhook_url))
      msg_title: git_push节点发布成功。
      msg_text: ${string.result}
